### ISSUE TITLE
Running browser.open.url throws error

### ISSUE THREAD

**Issue by dopinder100** [jakob-bagterp/browserist#517]
I installed the package with pip install browserist, then I have the following
```
browser = Browser()
browser.open.url("https://www.google.com/") 
```

I get the following error from running the Python script:
```

       The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Program Files\Python310\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Projects\Scrap-Rovo-Location\scrapv2.py", line 63, in <module>
    browser = Browser()
  File "D:\Program Files\Python310\lib\site-packages\browserist\browser\__main__.py", line 54, in __init__
    self._browser_driver: BrowserDriver = factory.get.browser_driver(settings)
  File "D:\Program Files\Python310\lib\site-packages\browserist\factory\get.py", line 22, in browser_driver
    return EdgeBrowserDriver(settings)
  File "D:\Program Files\Python310\lib\site-packages\browserist\model\browser\base\driver.py", line 30, in __init__
    if self.settings.check_connection and not helper.internet.has_connection():
  File "D:\Program Files\Python310\lib\site-packages\browserist\helper\internet.py", line 32, in has_connection
    with multiprocessing.Pool(processes=len(urls)) as pool:
  File "D:\Program Files\Python310\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "D:\Program Files\Python310\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "D:\Program Files\Python310\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "D:\Program Files\Python310\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "D:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Program Files\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "D:\Program Files\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by jakob-bagterp** [comment]
I haven’t seen this issue before and I can't replicate it. Seems like you’re running Python 3.10, right?

Suggestions to mitigate the issue:

- Maybe a quick fix would be trying to run your script with newer versions 3.11 or 3.12 of Python?
- Or try to bypass the `check_connection` part by setting it to `False`? Example below:

```python
from browserist import Browser, BrowserSettings

settings = BrowserSettings(check_connection = False)

with Browser(settings) as browser:
    browser.open.url("https://example.com")
```

**Comment by dopinder100** [comment]
I have upgraded my Python to 3.12.2

```
browser = Browser()
browser.open.url("https://www.google.com/") 

```
Running the above code still gives me the same error... please see below:

```
  File "D:\Program Files\Python312\Lib\site-packages\browserist\browser\__main__.py", line 54, in __init__
    self._browser_driver: BrowserDriver = factory.get.browser_driver(settings)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\browserist\factory\get.py", line 22, in browser_driver
    return EdgeBrowserDriver(settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\browserist\model\browser\base\driver.py", line 30, in __init__
    if self.settings.check_connection and not helper.internet.has_connection():
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\site-packages\browserist\helper\internet.py", line 32, in has_connection
    with multiprocessing.Pool(processes=len(urls)) as pool:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\multiprocessing\pool.py", line 215, in __init__
    self._repopulate_pool()
  File "D:\Program Files\Python312\Lib\multiprocessing\pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\multiprocessing\pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "D:\Program Files\Python312\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "D:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
```

**Comment by dopinder100** [comment]
```
    settings = BrowserSettings(check_connection = False)

    with Browser(settings) as browser:
        browser.open.url("https://www.example.com/")

```
Running the above code, gives me the following error:

```
[4140:9128:0223/023800.221:ERROR:policy_logger.cc(156)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.

DevTools listening on ws://127.0.0.1:62569/devtools/browser/4ca0be0d-e11d-4400-891a-d436690995ff
[4140:9128:0223/023800.684:ERROR:edge_auth_errors.cc(516)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:

[4140:9128:0223/023801.754:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
```

**Comment by jakob-bagterp** [comment]
> ```
>     settings = BrowserSettings(check_connection = False)
> 
>     with Browser(settings) as browser:
>         browser.open.url("https://www.example.com/")
> ```
> 
> Running the above code, gives me the following error:
> 
> ```
> [4140:9128:0223/023800.221:ERROR:policy_logger.cc(156)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
> 
> DevTools listening on ws://127.0.0.1:62569/devtools/browser/4ca0be0d-e11d-4400-891a-d436690995ff
> [4140:9128:0223/023800.684:ERROR:edge_auth_errors.cc(516)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:
> 
> [4140:9128:0223/023801.754:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
> ```

That doesn't seem to be an issue with Browserist, but with the browser driver for Edge you're using. Have you tried the stable version or maybe Chrome or Firefox as alternatives?

**Comment by jakob-bagterp** [comment]
> I have upgraded my Python to 3.12.2
> 
> ```
> browser = Browser()
> browser.open.url("https://www.google.com/") 
> ```
> 
> Running the above code still gives me the same error... please see below:
> 
> ```
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\browser\__main__.py", line 54, in __init__
>     self._browser_driver: BrowserDriver = factory.get.browser_driver(settings)
>                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\factory\get.py", line 22, in browser_driver
>     return EdgeBrowserDriver(settings)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\model\browser\base\driver.py", line 30, in __init__
>     if self.settings.check_connection and not helper.internet.has_connection():
>                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\helper\internet.py", line 32, in has_connection
>     with multiprocessing.Pool(processes=len(urls)) as pool:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\multiprocessing\context.py", line 119, in Pool
>     return Pool(processes, initializer, initargs, maxtasksperchild,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\multiprocessing\pool.py", line 215, in __init__
>     self._repopulate_pool()
>   File "D:\Program Files\Python312\Lib\multiprocessing\pool.py", line 306, in _repopulate_pool
>     return self._repopulate_pool_static(self._ctx, self.Process,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\multiprocessing\pool.py", line 329, in _repopulate_pool_static
>     w.start()
>   File "D:\Program Files\Python312\Lib\multiprocessing\process.py", line 121, in start
>     self._popen = self._Popen(self)
>                   ^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\multiprocessing\context.py", line 337, in _Popen
>     return Popen(process_obj)
>            ^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
>     _check_not_importing_main()
>   File "D:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
>     raise RuntimeError('''
> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
> 
>         To fix this issue, refer to the "Safe importing of main module"
>         section in https://docs.python.org/3/library/multiprocessing.html
> ```

I haven't seen this error before. Are you maybe running your automation in a multiprocessing setup with multiple instances of Browserist, or maybe you can elaborate a little more about the setup? Also, which versions of Selenium, browser (Edge, Chrome, Firefox), OS (Windows, macOS, Linux), etc. you're using?

**Comment by dopinder100** [comment]
I am very new to Selenium

I actually didn't configure anything. I have uninstalled Python 3.10 and installed Python 3.12.2

I didn't specify to use Edge, Chrome or Firefox.

> That doesn't seem to be an issue with Browserist, but with the browser driver for Edge you're using. Have you tried the stable version or maybe Chrome or Firefox as alternatives?

Could you please guide me, how do I let the script use the stable version of Firefox or Chrome?

> Are you maybe running your automation in a multiprocessing setup with multiple instances of Browserist, or maybe you can elaborate a little more about the setup? Also, which versions of Selenium, browser (Edge, Chrome, Firefox), OS (Windows, macOS, Linux), etc. you're using?

No, I am not running in a multiprocessing setup. I am on a standard and simple setup. I didn't configure anything. Every should be on default.

Please help me.

**Comment by dopinder100** [comment]
I am able to make some progress, by using the following:

```
settings = BrowserSettings(
   check_connection = False,
   type = BrowserType.FIREFOX
)

activities_url = "https://rovo.co/explore/activities"
activities_xpath = "//*[@id='bp3-tab-panel_explore-tabs_activities']/div/div"
activity_clickable_partial_xpath = "/div/div[1]"

with Browser(settings) as browser:
    activity_links: list[str] = []

    browser.open.url(activities_url)
    number_of_activities = browser.tool.count_elements(activities_xpath)

    for i in range(1, number_of_activities + 1):
        browser.click.button(f"{activities_xpath}[{i}]{activity_clickable_partial_xpath}")
        browser.wait.until.url.contains("https://rovo.co/plays/")
        activity_links.append(browser.get.url.current())
        browser.back()

    for i, link in enumerate(activity_links):
        browser.window.open.new_tab(link, f"tab_{i + 1}")
```

Basically, setting the browser type to Firefox, makes it work.

But, when the script tries to open an activity in a tab, it closes and throws the following error:

```
Traceback (most recent call last):
  File "D:\Projects\Scrap\scrapv2.py", line 87, in <module>
    browser.window.open.new_tab(link, f"tab_{i + 1}")
  File "D:\Program Files\Python312\Lib\site-packages\browserist\browser\window\open\__main__.py", line 36, in new_tab
    open_new_tab_or_window(self._browser_driver, self._controller, TabOrWindow.TAB, timeout, url, name)
  File "D:\Program Files\Python312\Lib\site-packages\browserist\browser\window\open\new_tab_or_window.py", line 23, in open_new_tab_or_window
    controller.add_handle(new_handle_id, name)
  File "D:\Program Files\Python312\Lib\site-packages\browserist\model\window\controller.py", line 26, in add_handle
    raise WindowHandleIdNotValidError(id)
browserist.exception.window_handle.WindowHandleIdNotValidError: Window handle ID has invalid format: a87dd3ed-070e-4c4a-b7fa-bdad864031c1
```

**Comment by dopinder100** [comment]
Any idea why the error?

**Comment by jakob-bagterp** [comment]
> I am able to make some progress, by using the following:
> 
> ```
> settings = BrowserSettings(
>    check_connection = False,
>    type = BrowserType.FIREFOX
> )
> 
> activities_url = "https://rovo.co/explore/activities"
> activities_xpath = "//*[@id='bp3-tab-panel_explore-tabs_activities']/div/div"
> activity_clickable_partial_xpath = "/div/div[1]"
> 
> with Browser(settings) as browser:
>     activity_links: list[str] = []
> 
>     browser.open.url(activities_url)
>     number_of_activities = browser.tool.count_elements(activities_xpath)
> 
>     for i in range(1, number_of_activities + 1):
>         browser.click.button(f"{activities_xpath}[{i}]{activity_clickable_partial_xpath}")
>         browser.wait.until.url.contains("https://rovo.co/plays/")
>         activity_links.append(browser.get.url.current())
>         browser.back()
> 
>     for i, link in enumerate(activity_links):
>         browser.window.open.new_tab(link, f"tab_{i + 1}")
> ```
> 
> Basically, setting the browser type to Firefox, makes it work.
> 
> But, when the script tries to open an activity in a tab, it closes and throws the following error:
> 
> ```
> Traceback (most recent call last):
>   File "D:\Projects\Scrap\scrapv2.py", line 87, in <module>
>     browser.window.open.new_tab(link, f"tab_{i + 1}")
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\browser\window\open\__main__.py", line 36, in new_tab
>     open_new_tab_or_window(self._browser_driver, self._controller, TabOrWindow.TAB, timeout, url, name)
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\browser\window\open\new_tab_or_window.py", line 23, in open_new_tab_or_window
>     controller.add_handle(new_handle_id, name)
>   File "D:\Program Files\Python312\Lib\site-packages\browserist\model\window\controller.py", line 26, in add_handle
>     raise WindowHandleIdNotValidError(id)
> browserist.exception.window_handle.WindowHandleIdNotValidError: Window handle ID has invalid format: a87dd3ed-070e-4c4a-b7fa-bdad864031c1
> ```
> 
> Anyway, even if this works, it will not be an ideal solution for my case.
> 
> This is because, I actually need to scroll down the activities page to lazy load more activities (by default the activities page only loads 10 or 20 activities on 1st loading). So, by using the current code, I will need to scroll down to load more activities, click on an activity, get the URL, go back, scroll down to load more activities, click on an activity, get the URL, go back, ... repeat...
> 
> Ideally, we should, open the activities page on tab 1, scroll down to load 200 activities (for example), then open the activity one by one, each on a new tab.
> 
> Can this be done?

Yes, it should be doable. However, I may need to investigate the `WindowHandleIdNotValidError` a little further. Did you always get this exception, or only sometimes?

**Comment by dopinder100** [comment]
I always get the same exception, every time. Any idea what is causing this exception?

**Comment by jakob-bagterp** [comment]
Please post your full script so I can assess. (You only added excerpts earlier.)

**Comment by dopinder100** [comment]
Any updates? I am still struggling to get this to work.
