### ISSUE TITLE
chromedriver

### ISSUE THREAD

**Issue by Roboxkin** [jakob-bagterp/browserist#695]
Hello! Please help me figure this out!
I keep getting an error after a new installation of Browserist.
I follow the instructions, but I can't run it.
What I did:
```Python
pip install browserist
pip install chromedriver
```
The code I'm trying to run:
```Python
from browserist import Browser

with Browser() as browser:
    browser.open.url("https://example.com")
    browser.wait.seconds(5)
```
My error:
```Python
D:\shorts\.venv\Scripts\python.exe D:\shorts\main.py 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^Traceback (most recent call last):
^  File "<string>", line 1, in <module>
^^  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main

  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 129, in _main
        exitcode = _main(fd, parent_sentinel)prepare(preparation_data)

  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 240, in prepare
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 129, in _main
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    prepare(preparation_data)
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 240, in prepare
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 280, in run_path
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\pkgutil.py", line 184, in <module>
    iter_importer_modules.register(
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\functools.py", line 892, in register
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    if _is_union_type(cls):
       ^^^^^^^^^^^^^^^^^^^    
main_content = runpy.run_path(main_path,
  File "C:\Users\Users\AppData\Local\Programs\Python\Python311\Lib\functools.py", line 842, in _is_union_type
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "D:\shorts\main.py", line 1, in <module>
    from browserist import Browser
  File "D:\shorts\.venv\Lib\site-packages\browserist\__init__.py", line 4, in <module>
    from typing import get_origin, Union
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 701, in _load_unlocked
KeyboardInterrupt
    from .browser.__main__ import Browser
  File "D:\shorts\.venv\Lib\site-packages\browserist\browser\__main__.py", line 5, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver
  File "D:\shorts\.venv\Lib\site-packages\selenium\webdriver\__init__.py", line 19, in <module>
    from .chrome.service import Service as ChromeService  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\shorts\.venv\Lib\site-packages\selenium\webdriver\chrome\service.py", line 20, in <module>
    from selenium.webdriver.chromium import service
  File "D:\shorts\.venv\Lib\site-packages\selenium\webdriver\chromium\service.py", line 21, in <module>
    from selenium.webdriver.common import service
  File "D:\shorts\.venv\Lib\site-packages\selenium\webdriver\common\service.py", line 18, in <module>
    import logging
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1032, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
KeyboardInterrupt

Process finished with exit code -1
```
I think the error is due to the driver, I already tried to put it in the patch, but it did not work.
Thank you very much!
(I do not speak English and use a translator)

**Comment by jakob-bagterp** [comment]
As it seems like you're running on Windows, the default browser isn't Chrome, but Edge. More info here:

https://jakob-bagterp.github.io/browserist/getting-started/browser-drivers/#microsoft-edge-driver

Also, you may want to update Chrome, Edge, etc. to their latest versions for the best results. And moreover update any relevant Python packages with this command:

```shell
pip install --upgrade <package>
```

I hope this solves your issues.
